### ISSUE TITLE
Line-local disable comment ignored?

### ISSUE THREAD

**Issue by objarni** [SublimeLinter/SublimeLinter-pylint#18]
Platform: Ubuntu 14.04
Subl: Sublime Text 3
Installed SublimeLinter-pylint through package control, otherwise working great!

I'm not able to disable a specific message through the line-comment method described in the README. 

Am I missing something?

Screenshot attached (sorry for the fuzzyness!)

![st3_pylint_disable_issue](https://cloud.githubusercontent.com/assets/68198/7766437/7ca8be62-0069-11e5-87f6-3aee724e1c71.png)

**Comment by NotSqrt** [comment]
Hi !

I have no problem whatsoever when using ``# pylint: disable=W0212``...

You can see the actual output of pylint in the console, when switching SublimeLinter to debug mode.

I suspect that this error comes from another linter, because pylint error codes are:
* a letter
* 4 digits

when here you have 3 digits..

**Comment by NotSqrt** [comment]
If this error indeed comes from pylint, the leading 0 might be stripped..
You can try with ``# pylint: disable=F0403``

**Comment by objarni** [comment]
Hi and thanks for ideas - I've tried prepending a '0' and it didn't help. I'll do some more debugging next week I'm sure and give you an update.

**Comment by objarni** [comment]
Oh, well this is embarrasing. I was using "Python Flake8 Lint". I've managed to disable the F403 mysterious error (which is flake8 specific, not pylint specific!) now. Sorry, my bad.
