### ISSUE TITLE
Incorrect "Module '%s' has no '%s' member"

### ISSUE THREAD

**Issue by jerlich** [SublimeLinter/SublimeLinter-pylint#21]
For example:
`Module 'numpy' has no 'zeros' member.`
But numpy indeed does have a zeros member and this code runs without error.

Sublime Text, Stable 3803
SublimeLinter 3.5.0
SublimeLinter-PyLint 1.3.1
![screen shot 2015-07-01 at 5 39 57 pm](https://cloud.githubusercontent.com/assets/2465395/8451764/421a845a-2018-11e5-8a47-ca84377b753a.png)

**Comment by NotSqrt** [comment]
Do you have a recent numpy ?
cf http://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members
In that case, it's not the fault of SublimeLinter-pylint ..

**Comment by jerlich** [comment]
```
$ pylint --version
No config file found, using default configuration
pylint 1.4.3, 
astroid 1.3.6, common 0.63.2
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
```

```
>>> import numpy
>>> numpy.__version__
'1.9.2'
```

**Comment by NotSqrt** [comment]
2 possibilities:

 * SublimeLinter-pylint uses a global pylint, so that it does not know the content of your virtualenvs, and can't find pylint. To fix that, you can provide paths to the virtualenv site-packages in the sublimelinter settings of pylint.
 * pylint gives this error even when called manually on the command line. In that case, it is yet another bug of numpy that does not expose its API properly for static analysis ..

**Comment by NotSqrt** [comment]
I tend to think that it's the last possibility, since I can reproduce it.
Then, sorry, I can't do anything about it ...

You can rely on tips from http://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members, or add ``# pylint: disable=E1101`` at the end of the import line.
