### ISSUE TITLE
`.pylintrc` not being detected / weird behavior

### ISSUE THREAD

**Issue by IOAyman** [SublimeLinter/SublimeLinter-pylint#39]
I have a project setup and open in SublimeText 3 along with this linter plugin. It works fine.  It detects the linting issues normally.

However, I want to make it detect my custom linting rules described in my `.pylintrc` file situated in the same project directory, so I provided the absolute path to it in the `.sublimelinterrc` file.  
The problem is that it's not being detected at all. The linter detects only the default config!

My `.sublimelinterrc` looks like this:
```json
{
  "@python": 2.7,
  "linters": {
    "pylint": {
      "@disable": false,
      "args": [""],
      "disable": "",
      "enable": "",
      "excludes": [],
      "paths": [],
      "rcfile": "/absolute/path/to/project/.pylintrc",
      "show-codes": false
    },
   ...
```

The command line ran in the console is the following:
```
SublimeLinter: pylint: project.py ['/usr/bin/python', '/usr/bin/pylint', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n'] 
```
That is clearly states two things:
1. It's not considering the `.pylintrc` in the config, which results in a bunch of errors, a score of -4/10. (running the same command from terminal on the same file I get a 10/10)
2. It's using the python2.7 interpreter.

**_Does this plugin consider per project `.sublimelinterrc` configurations?_**

- - -

I did another test; I created an ill-written `res.py` in the project root directory.
```python
msg = {
```

With the exact same configuration as before, the cmd run in the console is the following:
```
SublimeLinter: pylint: res.py ['/usr/bin/python2.7', '/usr/bin/pylint', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n', '', '--rcfile=/absolute/path/to/project/.pylintrc'] 
```
Reading that I understand two things:
1. It's using the python2.7 interpreter
2. It's considering the the `.pylintrc` provided in the `.sublimelinterrc` config

But then, in the console, there's neither a `pylint` output after the cmd nor a linter tooltip showing in sublime :/

- - -

The two situations confuse me 😕 Please help me if I'm getting something wrong?

**Comment by NotSqrt** [comment]
> Does this plugin consider per project .sublimelinterrc configurations?
This plugin uses the settings as made available by SublimeLinter, nothing specific to the plugin ..

1. This plugin is one of the rare plugins, if not the only one, that lints python code by running a command, not importing and running code. Which is why it still has trouble running pylint with the proper python version.
2. There might be a difference between background linting (when you change the code without save: sublimelinter copies the content to a tmp file and runs the linter) and linting after save (which uses the real file). There might be a bug in the settings that these cases use..

I don't really have the time to actively support this plugin, so I'm happy if people can provide good improvements !

**Comment by IOAyman** [comment]
> I don't really have the time to actively support this plugin, so I'm happy if people can provide good improvements !
I understand, thanks though :) 

I tried both cases, background and on-save, but the problem remains.

For the record, I believe there's a problem in applying the settings.

I added the link to `.pylintrc` to the user config instead of `.sublimelinterrc` (not really convenient for multiple projects), the linting works for one sub-directory (addons) .. but falls back to the default for the other one (bin) and the project root.

- - -
Not a promise, but I'll try to make some time to learn about STL plugins dev and contribute a solution.

**Comment by posita** [comment]
1. Do you have a `~/.pylintrc` file?
1. What's in your `/absolute/path/to/project/.pylintrc` file?
1. What happens when you attempt to run the following via the command line?

```sh
'/usr/bin/python2.7' '/usr/bin/pylint' "--msg-template='{line}:{column}:{msg_id}: {msg}'" '--module-rgx=.*' '--reports=n' '--persistent=n' '--rcfile=/absolute/path/to/project/.pylintrc' res.py
```

@IOAyman wrote [**_emphasis_** added]:
> … With **_the exact same configuration as before_**, the cmd run in the console is … .

4. Can you verify this assertion?

I can confirm that adding an explicit `SublimeLinter` → `linters` → `pylint` → `rcfile` entry to my `.sublime-project` file works as expected for me. My config:

```javascript
// ---- …/project/project.sublime-project ----
{
    "SublimeLinter": {
        "linters": {
            "pylint": {
                // Don't use ~/.pylintrc; show everything
                "rcfile": "/dev/null"
            }
        },
        "paths": {
            "linux": [],
            "osx": [
                "/…/.virtualenvs/project/bin"
            ],
            "windows": []
        }
    },
    "folders": [
        {
            "follow_symlinks": true,
            "path": "."
        }
    ],
    "settings": {
        "python_interpreter": "/…/.virtualenvs/project/bin/python",
        "suppress_python_not_found_error": false
    }
}
```

```javascript
// ---- …/project/.sublimelinterrc ----
{
    // https://github.com/SublimeLinter/SublimeLinter-pylint/issues/37
    "@python": "…/.virtualenvs/project/bin/python"
}
```

However, if I remove that entry from my `.sublime-project` file and add a `linters` → `pylint` → `rcfile` entry to my `.sublimelinterrc` file in my project directory, it appears to have no effect (i.e., having solely a `.sublimelinterrc` entry does **_not_** result in an added `--rcfile=…` command line argument). My config:

```javascript
// ---- …/project/project.sublime-project ----
{
    "SublimeLinter": {
        "linters": {
        },
        "paths": {
            "linux": [],
            "osx": [
                "/…/.virtualenvs/project/bin"
            ],
            "windows": []
        }
    },
    "folders": [
        {
            "follow_symlinks": true,
            "path": "."
        }
    ],
    "settings": {
        "python_interpreter": "/…/.virtualenvs/project/bin/python",
        "suppress_python_not_found_error": false
    }
}
```

```javascript
// ---- …/project/.sublimelinterrc ----
{
    // https://github.com/SublimeLinter/SublimeLinter-pylint/issues/37
    "@python": "…/.virtualenvs/project/bin/python",
    "linters": {
        "pylint": {
            // This doesn't seem to work here
            "rcfile": "/dev/null"
        }
    }
}
```

One observation: It looks like your command line with an explicit `--rcfile` has an extra blank argument that I can't reproduce on my end:

```
SublimeLinter: pylint: res.py ['/usr/bin/python2.7', …, '--persistent=n', '', '--rcfile=/absolute/path/to/project/.pylintrc'] 
                                                                          ^^^
                                                                   Why is this here?
```

What versions of `SublimeLinter` and `SublimeLinter-pylint` are you using?

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by larseggert** [comment]
Same issue here on the current version of SublimeLinter.
